repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: migrations/

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        exclude: migrations/