"""add help table for media groups

Revision ID: ad70fd085b89
Revises: 974ae69274fb
Create Date: 2024-02-09 06:03:38.265240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad70fd085b89'
down_revision = '974ae69274fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_group_media_file_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('from_message_id', sa.BigInteger(), nullable=False),
    sa.Column('file_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_group_media_file_ids')
    # ### end Alembic commands ###
