"""add unq constrate messages chat_id_var_name

Revision ID: b1d5bdb4189f
Revises: 1bb26a08633e
Create Date: 2024-01-13 13:01:57.474862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1d5bdb4189f'
down_revision = '1bb26a08633e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unq_messages_chat_id_variable_name', 'chat_settings', ['chat_id', 'variable_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unq_messages_chat_id_variable_name', 'chat_settings', type_='unique')
    # ### end Alembic commands ###
